# Generated by Django 4.2.5 on 2023-09-11 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="post_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 9, 11, 15, 8, 54, 335274)
            ),
        ),
    ]
