# Generated by Django 4.2.5 on 2023-09-11 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_alter_board_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="post_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 9, 11, 16, 41, 27, 630585)
            ),
        ),
    ]
